version: '3.5'

services:
  postgres:
    container_name: postgres13.3
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
 
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
